// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBExample-Web-Api-Key',
    appId: '1:123456789:web:example123',
    messagingSenderId: '123456789',
    projectId: 'app-task-manager',
    authDomain: 'app-task-manager.firebaseapp.com',
    storageBucket: 'app-task-manager.appspot.com',
    measurementId: 'G-EXAMPLE123',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBExample-Android-Api-Key',
    appId: '1:123456789:android:example123',
    messagingSenderId: '123456789',
    projectId: 'app-task-manager',
    storageBucket: 'app-task-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBExample-iOS-Api-Key',
    appId: '1:123456789:ios:example123',
    messagingSenderId: '123456789',
    projectId: 'app-task-manager',
    storageBucket: 'app-task-manager.appspot.com',
    iosBundleId: 'com.example.appTaskManager',
  );
}