targets:
  $default:
    builders:
      freezed:freezed:
        enabled: true
        options:
          # Generate freezed classes with copyWith, equality, toString
          map_factory: true
          union_factory: true
          
      json_serializable:json_serializable:
        enabled: true
        options:
          # Generate JSON serialization
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
          
      riverpod_generator:riverpod_generator:
        enabled: true
