// Mocks generated by Mockito 5.4.5 from annotations
// in app_agrihurbi/test/features/calculators/domain/usecases/execute_calculation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app_agrihurbi/features/calculators/domain/entities/calculation_history.dart'
    as _i9;
import 'package:app_agrihurbi/features/calculators/domain/entities/calculation_result.dart'
    as _i8;
import 'package:app_agrihurbi/features/calculators/domain/entities/calculator_category.dart'
    as _i7;
import 'package:app_agrihurbi/features/calculators/domain/entities/calculator_entity.dart'
    as _i6;
import 'package:app_agrihurbi/features/calculators/domain/repositories/calculator_repository.dart'
    as _i3;
import 'package:core/core.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CalculatorRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalculatorRepository extends _i1.Mock
    implements _i3.CalculatorRepository {
  MockCalculatorRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.CalculatorEntity>>>
      getAllCalculators() => (super.noSuchMethod(
            Invocation.method(
              #getAllCalculators,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.CalculatorEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.CalculatorEntity>>(
              this,
              Invocation.method(
                #getAllCalculators,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.CalculatorEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.CalculatorEntity>>>
      getCalculatorsByCategory(_i7.CalculatorCategory? category) =>
          (super.noSuchMethod(
            Invocation.method(
              #getCalculatorsByCategory,
              [category],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.CalculatorEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.CalculatorEntity>>(
              this,
              Invocation.method(
                #getCalculatorsByCategory,
                [category],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.CalculatorEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CalculatorEntity>> getCalculatorById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCalculatorById,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.CalculatorEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.CalculatorEntity>(
          this,
          Invocation.method(
            #getCalculatorById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.CalculatorEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.CalculationResult>> executeCalculation(
    String? calculatorId,
    Map<String, dynamic>? inputs,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeCalculation,
          [
            calculatorId,
            inputs,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i8.CalculationResult>>.value(
                _FakeEither_0<_i5.Failure, _i8.CalculationResult>(
          this,
          Invocation.method(
            #executeCalculation,
            [
              calculatorId,
              inputs,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.CalculationResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.CalculationHistory>>>
      getCalculationHistory() => (super.noSuchMethod(
            Invocation.method(
              #getCalculationHistory,
              [],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i9.CalculationHistory>>>.value(
                _FakeEither_0<_i5.Failure, List<_i9.CalculationHistory>>(
              this,
              Invocation.method(
                #getCalculationHistory,
                [],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i9.CalculationHistory>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> saveCalculationToHistory(
          _i9.CalculationHistory? historyItem) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCalculationToHistory,
          [historyItem],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #saveCalculationToHistory,
            [historyItem],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> removeFromHistory(
          String? historyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromHistory,
          [historyId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #removeFromHistory,
            [historyId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> clearHistory() =>
      (super.noSuchMethod(
        Invocation.method(
          #clearHistory,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #clearHistory,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.CalculatorEntity>>>
      searchCalculators(String? searchTerm) => (super.noSuchMethod(
            Invocation.method(
              #searchCalculators,
              [searchTerm],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.CalculatorEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.CalculatorEntity>>(
              this,
              Invocation.method(
                #searchCalculators,
                [searchTerm],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.CalculatorEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<String>>> getFavoriteCalculators() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteCalculators,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
            _FakeEither_0<_i5.Failure, List<String>>(
          this,
          Invocation.method(
            #getFavoriteCalculators,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<String>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> addToFavorites(
          String? calculatorId) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToFavorites,
          [calculatorId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #addToFavorites,
            [calculatorId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> removeFromFavorites(
          String? calculatorId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromFavorites,
          [calculatorId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #removeFromFavorites,
            [calculatorId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
}
