name: plantis_receituagro_monorepo
repository: https://github.com/seu-usuario/plantis-receituagro-monorepo

packages:
  - apps/*
  - packages/*

command:
  bootstrap:
    environment:
      sdk: ">=3.7.2 <4.0.0"
      flutter: ">=3.10.0"
    
  clean:
    hooks:
      pre: |
        echo "Limpando workspace Plantis & ReceitaAgro..."
    
scripts:
  # Comandos úteis para desenvolvimento
  analyze:
    run: flutter analyze
    description: Executa análise estática em todos os packages
    
  format:
    run: dart format --set-exit-if-changed .
    description: Formata código em todos os packages
    
  test:
    run: flutter test
    description: Executa testes em todos os packages
    
  # Build APK para todos os apps
  build:all:apk:
    run: |
      echo "Iniciando build APK RELEASE para todos os apps..."
      cd apps/app-plantis && flutter build apk --release && echo "✅ Plantis APK concluído" &&
      cd ../app-receituagro && flutter build apk --release && echo "✅ ReceitaAgro APK concluído" &&
      cd ../app-gasometer && flutter build apk --release && echo "✅ Gasometer APK concluído" &&
      echo "🎉 Todos os builds APK RELEASE foram concluídos com sucesso!"
    description: Build APK RELEASE para todos os três apps (Plantis, ReceitaAgro e Gasometer)
    
  build:all:apk:debug:
    run: |
      echo "Iniciando build APK DEBUG para todos os apps..."
      cd apps/app-plantis && flutter build apk --debug && echo "✅ Plantis APK DEBUG concluído" &&
      cd ../app-receituagro && flutter build apk --debug && echo "✅ ReceitaAgro APK DEBUG concluído" &&
      cd ../app-gasometer && flutter build apk --debug && echo "✅ Gasometer APK DEBUG concluído" &&
      echo "🎉 Todos os builds APK DEBUG foram concluídos com sucesso!"
    description: Build APK DEBUG para todos os três apps (desenvolvimento)
    
  build:all:apk:profile:
    run: |
      echo "Iniciando build APK PROFILE para todos os apps..."
      cd apps/app-plantis && flutter build apk --profile && echo "✅ Plantis APK PROFILE concluído" &&
      cd ../app-receituagro && flutter build apk --profile && echo "✅ ReceitaAgro APK PROFILE concluído" &&
      cd ../app-gasometer && flutter build apk --profile && echo "✅ Gasometer APK PROFILE concluído" &&
      echo "🎉 Todos os builds APK PROFILE foram concluídos com sucesso!"
    description: Build APK PROFILE para todos os três apps (análise de performance)
    
  # Builds para produção (individual por app)
  build:plantis:android:
    run: flutter build appbundle --release
    description: Build App Bundle para Play Store - Plantis (Plantas Domésticas)
    packageFilters:
      scope: "app_plantis"
      
  build:plantis:ios:
    run: flutter build ipa --release
    description: Build IPA para App Store - Plantis (Plantas Domésticas)
    packageFilters:
      scope: "app_plantis"
      
  build:receituagro:android:
    run: flutter build appbundle --release
    description: Build App Bundle para Play Store - ReceitaAgro (Pragas Agrícolas)
    packageFilters:
      scope: "app_receituagro"
      
  build:receituagro:ios:
    run: flutter build ipa --release
    description: Build IPA para App Store - ReceitaAgro (Pragas Agrícolas)
    packageFilters:
      scope: "app_receituagro"
      
  build:gasometer:android:
    run: flutter build appbundle --release
    description: Build App Bundle para Play Store - Gasometer (Controle de Combustível)
    packageFilters:
      scope: "app_gasometer"
      
  build:gasometer:ios:
    run: flutter build ipa --release
    description: Build IPA para App Store - Gasometer (Controle de Combustível)
    packageFilters:
      scope: "app_gasometer"
      
  # Scripts específicos por app
  run:plantis:
    run: flutter run
    description: Executa app Plantis (Plantas de Apartamento)
    packageFilters:
      scope: "app_plantis"
      
  run:receituagro:
    run: flutter run
    description: Executa app ReceitaAgro (Compêndio de Pragas)
    packageFilters:
      scope: "app_receituagro"
      
  run:gasometer:
    run: flutter run
    description: Executa app Gasometer (Controle de Combustível)
    packageFilters:
      scope: "app_gasometer"
      
  # Comandos específicos para desenvolvimento
  icons:plantis:
    run: flutter packages pub run flutter_launcher_icons:main -f flutter_launcher_icons-plantis.yaml
    description: Gera ícones para Plantis
    packageFilters:
      scope: "app_plantis"
      
  icons:receituagro:
    run: flutter packages pub run flutter_launcher_icons:main -f flutter_launcher_icons-receituagro.yaml
    description: Gera ícones para ReceitaAgro
    packageFilters:
      scope: "app_receituagro"