name: plantis_receituagro_monorepo
description: Monorepo contendo apps Plantis (plantas domésticas) e ReceitaAgro (pragas agrícolas)

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.10.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^6.3.3
  flutter_lints: ^6.0.0
  
  # Nota: Dependências específicas devem estar nos pubspec.yaml dos apps individuais
  cloud_firestore: any
  get: any
  supabase_flutter: any
  flutter: any
  hive: any
  intl: any
  shared_preferences: any
  firebase_core: any
  fl_chart: any
  flutter_staggered_grid_view: any
  uuid: any
  carousel_slider: any
  provider: any
  firebase_auth: any
  purchases_flutter: any
  url_launcher: any
  share_plus: any
  icons_plus: any
  firebase_analytics: any
  image_picker: any
  smooth_page_indicator: any
  html: any
  http: any
  rss_dart: any
  crypto: any
  path: any
  collection: any
  pluto_grid: any
  hive_flutter: any
  skeletonizer: any
  table_calendar: any
  connectivity_plus: any
  mask_text_input_formatter: any
  audioplayers: any
  flutter_local_notifications: any
  timezone: any
  firebase_crashlytics: any
  fnutrituti: any
  firebase_storage: any
  logging: any
  logger: any
  image: any
  synchronized: any
