name: plantis_receituagro_monorepo
description: Monorepo contendo apps Plantis (plantas domésticas) e ReceitaAgro (pragas agrícolas)

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^6.1.0
  flutter_lints: ^5.0.0
