// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa76MxuKL1zeo_QxuB0UiIb1rzIqDFrIk',
    appId: '1:131362278506:web:edb88da8028d69d3bb8e13',
    messagingSenderId: '131362278506',
    projectId: 'plantis-72458',
    authDomain: 'plantis-72458.firebaseapp.com',
    storageBucket: 'plantis-72458.firebasestorage.app',
    measurementId: 'G-D0E17X82G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzE9LcoqA2DDkiOsRLCt1ETkpV2TqLAyU',
    appId: '1:131362278506:android:094a4e30c8ca055bbb8e13',
    messagingSenderId: '131362278506',
    projectId: 'plantis-72458',
    storageBucket: 'plantis-72458.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6ekKCHE89371LJED3VyYLGDtD6oy48ng',
    appId: '1:131362278506:ios:2a885d7178910a2ebb8e13',
    messagingSenderId: '131362278506',
    projectId: 'plantis-72458',
    storageBucket: 'plantis-72458.firebasestorage.app',
    iosBundleId: 'br.com.agrimind.especiesorquideas',
  );
}
