# =============================================================================
# APP TASKOLIST - ANALYSIS OPTIONS
# =============================================================================
# Herda configurações empresariais do monorepo root
# App específico: Gerenciador de Tarefas (Riverpod + Clean Architecture)
# =============================================================================

# Herdar configurações empresariais do root
include: ../../analysis_options.yaml

analyzer:
  # Configurações específicas do app_taskolist
  exclude:
    # Excluir arquivos específicos do app
    - "lib/firebase_options.dart"
    
linter:
  rules:
    # Overrides específicos para app_taskolist se necessário
    # (manter mínimo possível para consistência)
    
    # Este app usa Riverpod - padrões mais rigorosos
    avoid_print: false # Permitir apenas durante desenvolvimento
