# =============================================================================
# APP PETIVETI - ANALYSIS OPTIONS
# =============================================================================
# Herda configurações empresariais do monorepo root
# App específico: Cuidado Veterinário (Provider + Notifications + Scheduling)
# =============================================================================

# Herdar configurações empresariais do root
include: ../../analysis_options.yaml

linter:
  rules:
    # Overrides específicos para app-petiveti se necessário
    # (manter mínimo possível para consistência)
    
    # Permitir prints em desenvolvimento (será removido em produção)
    avoid_print: false
