module.exports = ({
  useDB: true,
  populaDB: true,
  nomeDB: 'ReceituAgro_Cad',
  chaveIDB: 'compendioagricolaagrimind',
  chaveExport: '',
  dbSchema: {
    TBCONFIG: {
      _reference: false,
      _sync: false,
      objectId: { datatype: 'string', value: null, notnull: false, index: true },
      createdAt: { datatype: 'string', value: null, notnull: false, index: true },
      updatedAt: { datatype: 'string', value: null, notnull: false, index: true },
      IdReg: { datatype: 'string', value: null, notnull: true, index: true },
      Status: { datatype: 'boolean', value: true, notnull: false, index: true },
      string: { datatype: 'string', value: null, notnull: true, index: true },
      value: { datatype: 'string', value: null, notnull: false, index: true }
    },
    TBPRAGAS: {
      _reference: false,
      _sync: true,
      objectId: { datatype: 'string', value: null, notnull: false, index: true },
      createdAt: { datatype: 'string', value: null, notnull: false, index: true },
      updatedAt: { datatype: 'string', value: null, notnull: false, index: true },
      IdReg: { datatype: 'string', value: null, notnull: true, index: true },
      Status: { datatype: 'boolean', value: true, notnull: false, index: true },
      nomeComum: { datatype: 'string', value: null, notnull: true, index: false },
      nomeCientifico: { datatype: 'string', value: null, notnull: true, index: false },
      dominio: { datatype: 'string', value: null, notnull: false, index: false },
      reino: { datatype: 'string', value: null, notnull: false, index: false },
      subReino: { datatype: 'string', value: null, notnull: false, index: false },
      clado01: { datatype: 'string', value: null, notnull: false, index: false },
      clado02: { datatype: 'string', value: null, notnull: false, index: false },
      clado03: { datatype: 'string', value: null, notnull: false, index: false },
      superDivisao: { datatype: 'string', value: null, notnull: false, index: false },
      divisao: { datatype: 'string', value: null, notnull: false, index: false },
      subDivisao: { datatype: 'string', value: null, notnull: false, index: false },
      classe: { datatype: 'string', value: null, notnull: false, index: false },
      subClasse: { datatype: 'string', value: null, notnull: false, index: false },
      superOrdem: { datatype: 'string', value: null, notnull: false, index: false },
      ordem: { datatype: 'string', value: null, notnull: false, index: false },
      subOrdem: { datatype: 'string', value: null, notnull: false, index: false },
      infraOrdem: { datatype: 'string', value: null, notnull: false, index: false },
      superFamilia: { datatype: 'string', value: null, notnull: false, index: false },
      familia: { datatype: 'string', value: null, notnull: false, index: false },
      subFamilia: { datatype: 'string', value: null, notnull: false, index: false },
      tribo: { datatype: 'string', value: null, notnull: false, index: false },
      subTribo: { datatype: 'string', value: null, notnull: false, index: false },
      genero: { datatype: 'string', value: null, notnull: false, index: false },
      especie: { datatype: 'string', value: null, notnull: false, index: false },
      tipoPraga: { datatype: 'string', value: null, notnull: true, index: true }
    },
    TBFITOSSANITARIOS: {
      _reference: false,
      _sync: true,
      objectId: { datatype: 'string', value: null, notnull: false, index: true },
      createdAt: { datatype: 'string', value: null, notnull: false, index: true },
      updatedAt: { datatype: 'string', value: null, notnull: false, index: true },
      IdReg: { datatype: 'string', value: null, notnull: true, index: true },
      Status: { datatype: 'boolean', value: true, notnull: false, index: true },
      nomeComum: { datatype: 'string', value: null, notnull: true, index: true },
      nomeTecnico: { datatype: 'string', value: null, notnull: true, index: true },
      classeAgronomica: { datatype: 'string', value: null, notnull: true, index: false },
      fabricante: { datatype: 'string', value: null, notnull: true, index: true },
      classAmbiental: { datatype: 'string', value: null, notnull: true, index: false },
      comercializado: { datatype: 'number', value: 1, notnull: true, index: true },
      corrosivo: { datatype: 'string', value: null, notnull: false, index: false },
      inflamavel: { datatype: 'string', value: null, notnull: false, index: false },
      formulacao: { datatype: 'string', value: null, notnull: true, index: false },
      modoAcao: { datatype: 'string', value: null, notnull: false, index: false },
      mapa: { datatype: 'string', value: null, notnull: false, index: false },
      toxico: { datatype: 'string', value: null, notnull: false, index: false },
      ingredienteAtivo: { datatype: 'string', value: null, notnull: false, index: true },
      quantProduto: { datatype: 'string', value: null, notnull: false, index: false },
      elegivel: { datatype: 'boolean', value: false, notnull: true, index: true }
    },
    TBPLANTASINF: {
      _reference: false,
      _sync: true,
      objectId: { datatype: 'string', value: null, notnull: false, index: true },
      createdAt: { datatype: 'string', value: null, notnull: false, index: true },
      updatedAt: { datatype: 'string', value: null, notnull: false, index: true },
      IdReg: { datatype: 'string', value: null, notnull: true, index: true },
      Status: { datatype: 'boolean', value: true, notnull: false, index: true },
      fkIdPraga: { datatype: 'string', value: null, notnull: true, index: true },
      ciclo: { datatype: 'string', value: null, notnull: false, index: false },
      reproducao: { datatype: 'string', value: null, notnull: false, index: false },
      habitat: { datatype: 'string', value: null, notnull: false, index: false },
      adaptacoes: { datatype: 'string', value: null, notnull: false, index: false },
      altura: { datatype: 'string', value: null, notnull: false, index: false },
      filotaxia: { datatype: 'string', value: null, notnull: false, index: false },
      formaLimbo: { datatype: 'string', value: null, notnull: false, index: false },
      superficie: { datatype: 'string', value: null, notnull: false, index: false },
      consistencia: { datatype: 'string', value: null, notnull: false, index: false },
      nervacao: { datatype: 'string', value: null, notnull: false, index: false },
      nervacaoComprimento: { datatype: 'string', value: null, notnull: false, index: false },
      inflorescencia: { datatype: 'string', value: null, notnull: false, index: false },
      perianto: { datatype: 'string', value: null, notnull: false, index: false },
      tipologiaFruto: { datatype: 'string', value: null, notnull: false, index: false },
      observacoes: { datatype: 'string', value: null, notnull: false, index: false }
    },
    TBPRAGASINF: {
      _reference: false,
      _sync: true,
      objectId: { datatype: 'string', value: null, notnull: false, index: true },
      createdAt: { datatype: 'string', value: null, notnull: false, index: true },
      updatedAt: { datatype: 'string', value: null, notnull: false, index: true },
      IdReg: { datatype: 'string', value: null, notnull: true, index: true },
      Status: { datatype: 'boolean', value: true, notnull: false, index: true },
      fkIdPraga: { datatype: 'string', value: null, notnull: true, index: true },
      descrisao: { datatype: 'string', value: null, notnull: false, index: false },
      sintomas: { datatype: 'string', value: null, notnull: false, index: false },
      bioecologia: { datatype: 'string', value: null, notnull: false, index: false },
      controle: { datatype: 'string', value: null, notnull: false, index: false }
    },
    TBDIAGNOSTICO: {
      _reference: false,
      _sync: true,
      objectId: { datatype: 'string', value: null, notnull: false, index: true },
      createdAt: { datatype: 'string', value: null, notnull: false, index: true },
      updatedAt: { datatype: 'string', value: null, notnull: false, index: true },
      IdReg: { datatype: 'string', value: null, notnull: true, index: true },
      Status: { datatype: 'boolean', value: true, notnull: false, index: true },
      fkIdDefensivo: { datatype: 'string', value: null, notnull: true, index: true },
      fkIdCultura: { datatype: 'string', value: null, notnull: true, index: true },
      fkIdPraga: { datatype: 'string', value: null, notnull: true, index: true },
      dsMin: { datatype: 'string', value: null, notnull: false, index: false },
      dsMax: { datatype: 'string', value: null, notnull: false, index: false },
      um: { datatype: 'string', value: null, notnull: false, index: false },
      minAplicacaoT: { datatype: 'string', value: null, notnull: false, index: false },
      maxAplicacaoT: { datatype: 'string', value: null, notnull: false, index: false },
      umT: { datatype: 'string', value: null, notnull: false, index: false },
      minAplicacaoA: { datatype: 'string', value: null, notnull: false, index: false },
      maxAplicacaoA: { datatype: 'string', value: null, notnull: false, index: false },
      umA: { datatype: 'string', value: null, notnull: false, index: false },
      intervalo: { datatype: 'string', value: null, notnull: false, index: false },
      intervalo2: { datatype: 'string', value: null, notnull: false, index: false },
      epocaAplicacao: { datatype: 'string', value: null, notnull: false, index: false }
    },
    TBFITOSSANITARIOSINFO: {
      _reference: false,
      _sync: true,
      objectId: { datatype: 'string', value: null, notnull: false, index: true },
      createdAt: { datatype: 'string', value: null, notnull: false, index: true },
      updatedAt: { datatype: 'string', value: null, notnull: false, index: true },
      IdReg: { datatype: 'string', value: null, notnull: true, index: true },
      Status: { datatype: 'boolean', value: true, notnull: false, index: true },
      fkIdDefensivo: { datatype: 'string', value: null, notnull: true, index: true },
      embalagens: { datatype: 'string', value: null, notnull: false, index: false },
      tecnologia: { datatype: 'string', value: null, notnull: false, index: false },
      pHumanas: { datatype: 'string', value: null, notnull: false, index: false },
      pAmbiental: { datatype: 'string', value: null, notnull: false, index: false },
      manejoResistencia: { datatype: 'string', value: null, notnull: false, index: false },
      compatibilidade: { datatype: 'string', value: null, notnull: false, index: false },
      manejoIntegrado: { datatype: 'string', value: null, notnull: false, index: false }
    },
    TBCULTURAS: {
      _reference: false,
      _sync: true,
      objectId: { datatype: 'string', value: null, notnull: false, index: true },
      createdAt: { datatype: 'string', value: null, notnull: false, index: true },
      updatedAt: { datatype: 'string', value: null, notnull: false, index: true },
      IdReg: { datatype: 'string', value: null, notnull: true, index: true },
      Status: { datatype: 'boolean', value: true, notnull: false, index: true },
      cultura: { datatype: 'string', value: null, notnull: true, index: false }
    },
    TBFAVORITOS: {
      _reference: false,
      _sync: true,
      objectId: { datatype: 'string', value: null, notnull: false, index: true },
      createdAt: { datatype: 'string', value: null, notnull: false, index: true },
      updatedAt: { datatype: 'string', value: null, notnull: false, index: true },
      IdReg: { datatype: 'string', value: null, notnull: true, index: true },
      Status: { datatype: 'boolean', value: true, notnull: false, index: true }
    }
  },
  files: [
    { table: 'TBFITOSSANITARIOS', file: 'TBFITOSSANITARIOS0.json' },
    { table: 'TBFITOSSANITARIOS', file: 'TBFITOSSANITARIOS1.json' },
    { table: 'TBFITOSSANITARIOS', file: 'TBFITOSSANITARIOS2.json' },
    { table: 'TBPLANTASINF', file: 'TBPLANTASINF0.json' },
    { table: 'TBPRAGASINF', file: 'TBPRAGASINF0.json' },
    { table: 'TBPRAGAS', file: 'TBPRAGAS0.json' },
    { table: 'TBCULTURAS', file: 'TBCULTURAS0.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO0.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO1.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO2.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO3.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO4.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO5.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO6.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO7.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO8.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO10.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO11.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO12.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO13.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO14.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO15.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO16.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO17.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO18.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO19.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO20.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO21.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO22.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO23.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO24.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO26.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO27.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO28.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO29.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO30.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO31.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO32.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO33.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO34.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO35.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO36.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO37.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO38.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO39.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO40.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO41.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO42.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO43.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO44.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO45.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO46.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO47.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO48.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO49.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO50.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO51.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO52.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO53.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO54.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO55.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO56.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO57.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO58.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO59.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO60.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO61.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO62.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO63.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO64.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO65.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO66.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO67.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO68.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO69.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO70.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO71.json' },
    { table: 'TBDIAGNOSTICO', file: 'TBDIAGNOSTICO72.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO0.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO1.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO2.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO3.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO4.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO5.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO6.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO7.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO8.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO9.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO10.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO11.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO12.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO13.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO14.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO15.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO16.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO17.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO18.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO19.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO20.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO21.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO22.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO23.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO24.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO25.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO26.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO27.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO28.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO29.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO30.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO31.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO32.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO33.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO34.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO35.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO36.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO37.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO38.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO39.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO40.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO41.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO42.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO43.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO44.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO45.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO46.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO47.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO48.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO49.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO50.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO51.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO52.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO53.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO54.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO55.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO56.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO57.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO58.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO59.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO60.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO61.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO62.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO63.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO64.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO65.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO66.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO67.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO68.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO69.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO70.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO71.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO72.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO73.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO74.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO75.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO76.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO77.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO78.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO79.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO80.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO81.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO82.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO83.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO84.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO85.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO86.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO87.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO88.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO89.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO90.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO91.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO92.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO93.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO94.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO95.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO96.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO97.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO98.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO99.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO100.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO101.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO102.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO103.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO104.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO105.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO106.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO107.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO108.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO109.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO110.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO111.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO112.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO113.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO114.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO115.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO116.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO117.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO118.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO119.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO120.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO121.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO122.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO123.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO124.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO125.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO126.json' },
    { table: 'TBFITOSSANITARIOSINFO', file: 'TBFITOSSANITARIOSINFO127.json' }
  ]
})
