import 'package:hive/hive.dart';
import '../../domain/entities/example_entity.dart';

part 'example_model.g.dart'; // Generated file

/// Example Hive model
/// Mutable version for local storage
/// TypeAdapter will be generated by hive_generator
@HiveType(typeId: 0) // Unique typeId for each model
class ExampleModel extends HiveObject {
  ExampleModel({
    required this.id,
    required this.name,
    this.description,
    this.createdAt,
    this.updatedAt,
    this.isDirty = false,
    this.userId,
    this.moduleName = 'example',
  });

  @HiveField(0)
  String id;

  @HiveField(1)
  String name;

  @HiveField(2)
  String? description;

  @HiveField(3)
  DateTime? createdAt;

  @HiveField(4)
  DateTime? updatedAt;

  @HiveField(5)
  bool isDirty;

  @HiveField(6)
  String? userId;

  @HiveField(7)
  String moduleName;

  /// Convert model to entity
  ExampleEntity toEntity() {
    return ExampleEntity(
      id: id,
      name: name,
      description: description,
      createdAt: createdAt,
      updatedAt: updatedAt,
      isDirty: isDirty,
      userId: userId,
      moduleName: moduleName,
    );
  }

  /// Create model from entity
  factory ExampleModel.fromEntity(ExampleEntity entity) {
    return ExampleModel(
      id: entity.id,
      name: entity.name,
      description: entity.description,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
      isDirty: entity.isDirty,
      userId: entity.userId,
      moduleName: entity.moduleName,
    );
  }

  /// Create model from JSON (Firebase)
  factory ExampleModel.fromJson(Map<String, dynamic> json) {
    return ExampleModel(
      id: json['id'] as String,
      name: json['name'] as String,
      description: json['description'] as String?,
      createdAt: json['createdAt'] != null
          ? DateTime.parse(json['createdAt'] as String)
          : null,
      updatedAt: json['updatedAt'] != null
          ? DateTime.parse(json['updatedAt'] as String)
          : null,
      isDirty: json['isDirty'] as bool? ?? false,
      userId: json['userId'] as String?,
      moduleName: json['moduleName'] as String? ?? 'example',
    );
  }

  /// Convert model to JSON (Firebase)
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'description': description,
      'createdAt': createdAt?.toIso8601String(),
      'updatedAt': updatedAt?.toIso8601String(),
      'isDirty': isDirty,
      'userId': userId,
      'moduleName': moduleName,
    };
  }
}
