/// Constants for the medications page UI elements, dimensions, and timings
class MedicationsConstants {
  MedicationsConstants._();
  static const int tabCount = 4;
  static const double tabIconSize = 16.0;
  static const double errorIconSize = 64.0;
  static const double pageContentPadding = 16.0;
  static const double searchFiltersSpacing = 8.0;
  static const double errorContentSpacing = 16.0;
  static const double dialogContentSpacing = 16.0;
  static const double medicationCardHeight = 120.0;
  static const double cardBottomSpacing = 8.0;
  static const double errorTextSize = 16.0;
  static const Duration loadingTimeout = Duration(seconds: 10);
  static const int reasonTextFieldMaxLines = 3;
  static const String allMedicationsTitle = 'Medicamentos';
  static const String petMedicationsTitle = 'Medicamentos do Pet';
  static const String searchHintText = 'Buscar medicamentos...';
  static const String addMedicationTooltip = 'Adicionar Medicamento';
  static const String refreshTooltip = 'Atualizar';
  static const String allTabTitle = 'Todos';
  static const String activeTabTitle = 'Ativos';
  static const String expiringTabTitle = 'Vencendo';
  static const String statisticsTabTitle = 'Estatísticas';
  static const String noActiveMedications = 'Nenhum medicamento ativo no momento';
  static const String noExpiringMedications = 'Nenhum medicamento próximo ao vencimento';
  static const String noMedicationsFound = 'Nenhum medicamento encontrado';
  static const String retryButtonText = 'Tentar Novamente';
  static const String cancelButtonText = 'Cancelar';
  static const String deleteButtonText = 'Excluir';
  static const String discontinueButtonText = 'Descontinuar';
  static const String deleteMedicationTitle = 'Excluir Medicamento';
  static const String discontinueMedicationTitle = 'Descontinuar Medicamento';
  static const String medicationDeletedMessage = 'Medicamento excluído com sucesso';
  static const String medicationDiscontinuedMessage = 'Medicamento descontinuado';
  static const String discontinuationReasonLabel = 'Motivo da descontinuação';
  static const String addMedicationRoute = '/medications/add';
  static const String detailsRoute = '/medications/details';
  static const String editRoute = '/medications/edit';
}