name: app_nebulalist
description: NebulaList - A modern task management application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: 3.35.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core Package - Shared services (Firebase, Riverpod, Hive, GetIt, Injectable, dartz, equatable)
  core:
    path: ../../packages/core

  # State Management (Riverpod with code generation)
  flutter_riverpod: any
  riverpod_annotation: any

  # Dependency Injection
  get_it: any
  injectable: any

  # Functional Programming
  dartz: any

  # Local Storage
  hive: any
  hive_flutter: any
  path_provider: any

  # Firebase
  cloud_firestore: any
  firebase_auth: any
  firebase_storage: any
  firebase_analytics: any
  firebase_core: any

  # Navigation
  go_router: any

  # Utils
  uuid: any
  equatable: any
  intl: any
  shared_preferences: any
  url_launcher: any

  # Freezed (immutable state)
  freezed_annotation: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: any
  hive_generator: any
  riverpod_generator: any
  injectable_generator: any
  freezed: any
  json_serializable: any

  # Testing
  mocktail: any

  # Linting
  custom_lint: any
  riverpod_lint: any

flutter:
  uses-material-design: true

  # TODO: Add your assets here
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # TODO: Add custom fonts if needed
  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: assets/fonts/YourFont-Regular.ttf
  #       - asset: assets/fonts/YourFont-Bold.ttf
  #         weight: 700
