# =============================================================================
# APP GASOMETER - ANALYSIS OPTIONS
# =============================================================================
# Herda configurações empresariais do monorepo root
# App específico: Controle de Veículos (Provider + Hive + Analytics)
# =============================================================================

# Herdar configurações empresariais do root
include: ../../analysis_options.yaml

analyzer:
  # Configurações específicas do app-gasometer
  exclude:
    # Excluir arquivos específicos do app
    - "lib/firebase_options.dart"
    
linter:
  rules:
    # Overrides específicos para app-gasometer se necessário
    # (manter mínimo possível para consistência)
    
    # Permitir prints em desenvolvimento (será removido em produção)
    avoid_print: false
