targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        enabled: true
        options:
          auto_register: true
          # Generate injectable config
          class_name_pattern: "Injectable*"
          
      hive_generator:hive_generator:
        enabled: true
        options:
          # Generate Hive adapters
          part_name_pattern: "{name}.g.dart"
          
      freezed:freezed:
        enabled: true
        options:
          # Generate freezed classes with copyWith, equality, toString
          map_factory: true
          union_factory: true
          
      json_serializable:json_serializable:
        enabled: true
        options:
          # Generate JSON serialization
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true

# Global options
global_options:
  injectable_generator:injectable_builder:
    options:
      # Enable auto registration of @injectable classes
      auto_register: true
      # Include dev dependencies in generation
      include_dev_dependencies: false