name: termostecnicos
description: A new Flutter project.

publish_to: 'none'

version: 2024.10.05+20241005

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Monorepo shared package
  core:
    path: ../../packages/core

  # UI
  cupertino_icons: ^1.0.8

  # State Management (Riverpod - replacing GetX)
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Dependency Injection
  get_it: ^8.0.2
  injectable: ^2.5.1

  # Functional Programming
  dartz: ^0.10.1
  equatable: ^2.0.7

  # Utils
  logger: ^2.4.0

  # App-specific
  flutter_quill: ^11.0.0
  flutter_tts: ^4.0.2
  app_settings: ^5.1.1
  purchases_ui_flutter: ^9.8.0
  flutter_localization: ^0.2.1
  flutter_localizations:
    sdk: flutter
  skeletonizer: ^1.4.2
  flutter_staggered_grid_view: ^0.7.0

  # Navigation (will replace GetX)
  go_router: ^16.2.4

  # Legacy dependencies (used directly in lib/core files)
  # TODO: Remove after full migration to Riverpod
  get: ^4.6.6

  # Dependencies from core but used directly in app code
  # (Required for direct imports per analyzer)
  hive: any
  shared_preferences: any
  firebase_core: any
  icons_plus: any
  url_launcher: any
  google_mobile_ads: any
  intl: any
  purchases_flutter: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0

  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.0
  injectable_generator: ^2.6.2

  # Custom Linting
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/database/json/administracao/
    - assets/database/json/agricultura/
    - assets/database/json/arquitetura/
    - assets/database/json/biologia/
    - assets/database/json/direito/
    - assets/database/json/economia/
    - assets/database/json/fisica/
    - assets/database/json/geografia/
    - assets/database/json/informatica/
    - assets/database/json/matematica/
    - assets/database/json/medicina/
    - assets/database/json/quimica/
    - assets/icons_app/
    - assets/
    - lib/assets/
    - lib/assets/icons/
    - lib/assets/billing/
