// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM_xeIQR83_YiOgE_FXt09TzqVH02HCv0',
    appId: '1:1015632283781:web:9b8729e960d061ee1541ec',
    messagingSenderId: '1015632283781',
    projectId: 'minigames-33fe5',
    authDomain: 'minigames-33fe5.firebaseapp.com',
    storageBucket: 'minigames-33fe5.firebasestorage.app',
    measurementId: 'G-P99S1GH2NS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR3ugM5sfxcb-Hy6P9z7pnfUOvRD12O_4',
    appId: '1:1015632283781:android:127cbdae9e4269e31541ec',
    messagingSenderId: '1015632283781',
    projectId: 'minigames-33fe5',
    storageBucket: 'minigames-33fe5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChsARHBux9w6h8qwzdmtFl94vUq25xrYw',
    appId: '1:1015632283781:ios:5b8fda7e15a1271d1541ec',
    messagingSenderId: '1015632283781',
    projectId: 'minigames-33fe5',
    storageBucket: 'minigames-33fe5.firebasestorage.app',
    iosBundleId: 'br.com.agrimind.minigames',
  );
}
