# =============================================================================
# APP RECEITUAGRO - ANALYSIS OPTIONS
# =============================================================================
# Herda configurações empresariais do monorepo root
# App específico: Diagnóstico Agrícola (Provider + Static Data + Hive)
# =============================================================================

# Herdar configurações empresariais do root
include: ../../analysis_options.yaml

analyzer:
  # Configurações específicas do app-receituagro
  exclude:
    # Excluir arquivos específicos do app
    - "lib/firebase_options.dart"
    
linter:
  rules:
    # Overrides específicos para app-receituagro se necessário
    # (manter mínimo possível para consistência)
    
    # Permitir prints em desenvolvimento (será removido em produção)
    avoid_print: false
