# =============================================================================
# CORE PACKAGE - ANALYSIS OPTIONS
# =============================================================================
# Herda configurações empresariais do monorepo root
# Package: Serviços compartilhados (Firebase, RevenueCat, Hive, etc.)
# =============================================================================

# Herdar configurações empresariais do root
include: ../../analysis_options.yaml

analyzer:
  # Configurações específicas do core package
  exclude:
    # Excluir apenas arquivos realmente necessários
    - "example/**"
    
linter:
  rules:
    # Core package - padrões MAIS rigorosos (API pública)
    # 
    # Documentação obrigatória para toda API pública
    public_member_api_docs: true
    
    # Não permitir prints em package core
    avoid_print: true
    
    # Enforce const constructors sempre que possível
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
