# Build configuration for Drift code generation
targets:
  $default:
    builders:
      drift_dev:
        enabled: true
        options:
          # Gera arquivos .drift.dart ao invés de .g.dart
          use_data_class_name_for_companions: true
          use_column_name_as_json_key_when_defined_in_moor_file: true
          
          # Opções de geração
          generate_connect_constructor: true
          
          # Tabelas SQL standalone (opcional)
          # sql:
          #   enabled: true
          
          # Store date time values as unix timestamps
          store_date_time_values_as_text: false
