name: receituagro_web
description: "Receituagro Web Application - Agricultural diagnosis and recommendations"

publish_to: 'none'

version: 2024.08.05+2

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core Package
  core:
    path: ../../packages/core
  
  # UI Components
  cupertino_icons: ^1.0.8
  icons_plus: ^5.0.0
  google_fonts: ^6.2.1
  carousel_slider: ^5.1.1
  flutter_staggered_grid_view: ^0.7.0
  skeletonizer: ^2.1.0+1
  
  # State Management
  get: ^4.7.2
  provider: ^6.1.5
  
  # Firebase & Database
  firebase_analytics: ^12.0.2
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  supabase_flutter: ^2.9.1
  
  # Utilities
  share_plus: ^12.0.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  html_unescape: ^2.0.0
  package_info_plus: ^8.3.0
  logger: ^2.6.0
  url_launcher: ^6.3.2
  app_settings: ^6.1.1
  device_info_plus: ^11.5.0
  
  # Localization
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/billing/
    - lib/assets/icons/
    - assets/
