import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../../../../core/interfaces/usecase.dart' as local;
import '../../domain/entities/promo_content.dart';
import '../../domain/usecases/get_promo_content.dart';
import '../../domain/usecases/submit_pre_registration.dart';
import '../../domain/usecases/track_analytics.dart';
import '../states/promo_state.dart';
import 'promo_providers.dart';

part 'promo_provider.g.dart';


// Provider generated by @riverpod

@riverpod
class PromoNotifier extends _$PromoNotifier {
  late final GetPromoContent _getPromoContent;
  late final SubmitPreRegistration _submitPreRegistration;
  late final TrackAnalytics _trackAnalytics;

  @override
  PromoState build() {
    _getPromoContent = ref.watch(getPromoContentProvider);
    _submitPreRegistration = ref.watch(submitPreRegistrationProvider);
    _trackAnalytics = ref.watch(trackAnalyticsProvider);
    return const PromoState.initial();
  }

  /// Carrega o conteúdo promocional
  Future<void> loadPromoContent() async {
    if (state.isLoading) return;
    
    state = state.copyWith(isLoading: true, error: null);

    final result = await _getPromoContent(const local.NoParams());
    
    // Verifica se o provider ainda está montado após a operação assíncrona
    try {
      result.fold(
        (failure) => state = state.copyWith(
          isLoading: false,
          error: failure.message,
        ),
        (promoContent) => state = state.copyWith(
          isLoading: false,
          promoContent: promoContent,
          error: null,
        ),
      );
    } catch (e) {
      // Provider foi disposed durante a operação assíncrona
      return;
    }
  }

  /// Submete pré-cadastro
  Future<void> submitPreRegistration(String email) async {
    if (state.isSubmittingPreRegistration) return;

    state = state.copyWith(isSubmittingPreRegistration: true, preRegistrationError: null);

    final result = await _submitPreRegistration(email);
    
    result.fold(
      (failure) => state = state.copyWith(
        isSubmittingPreRegistration: false,
        preRegistrationError: failure.message,
      ),
      (_) => state = state.copyWith(
        isSubmittingPreRegistration: false,
        preRegistrationSuccess: true,
        preRegistrationError: null,
      ),
    );
  }

  /// Expande/colapsa uma FAQ
  void toggleFAQ(String faqId) {
    final currentContent = state.promoContent;
    if (currentContent == null) return;

    final updatedFaqs = currentContent.faqs.map((faq) {
      if (faq.id == faqId) {
        return faq.copyWith(isExpanded: !faq.isExpanded);
      }
      return faq;
    }).toList();

    final updatedContent = PromoContent(
      appName: currentContent.appName,
      appVersion: currentContent.appVersion,
      appDescription: currentContent.appDescription,
      appTagline: currentContent.appTagline,
      features: currentContent.features,
      testimonials: currentContent.testimonials,
      faqs: updatedFaqs,
      screenshots: currentContent.screenshots,
      launchInfo: currentContent.launchInfo,
      contactInfo: currentContent.contactInfo,
    );

    state = state.copyWith(promoContent: updatedContent);
  }

  /// Altera o screenshot atual
  void changeScreenshot(int index) {
    state = state.copyWith(currentScreenshotIndex: index);
  }

  /// Mostra/esconde o diálogo de pré-cadastro
  void togglePreRegistrationDialog() {
    state = state.copyWith(
      showPreRegistrationDialog: !state.showPreRegistrationDialog,
      preRegistrationSuccess: false,
      preRegistrationError: null,
    );
  }

  /// Registra evento de analytics
  Future<void> trackEvent(String event, {Map<String, dynamic>? parameters}) async {
    await _trackAnalytics(TrackAnalyticsParams(
      event: event,
      parameters: parameters ?? {},
    ));
  }

  /// Limpa mensagens de erro/sucesso
  void clearMessages() {
    state = state.copyWith(
      error: null,
      preRegistrationError: null,
      preRegistrationSuccess: false,
    );
  }
}
