name: app_agrihurbi
description: "Sistema completo de gestão agropecuária com calculadoras especializadas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Package - Serviços compartilhados do monorepo
  core:
    path: ../../packages/core

  # State Management
  provider: ^6.1.1
  
  # Architecture
  dartz: ^0.10.1            # Either/Option functional programming
  equatable: ^2.0.7         # Entity equality
  
  # Dependency Injection
  get_it: ^8.2.0           # Service locator
  injectable: ^2.3.2        # Code generation para DI
  
  # Navigation
  go_router: ^16.1.0        # Substitui GetX navigation
  
  # Network
  dio: ^5.9.0              # HTTP client
  connectivity_plus: ^6.1.5
  
  # RSS & External Data (será adicionado na Fase 5)
  
  # Utils específicos do app
  intl: ^0.20.2
  
  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  
  # Weather & Location
  geolocator: ^13.0.1
  weather: ^3.1.1
  
  # Charts for calculators
  fl_chart: ^0.69.2
  
  # Date & Time
  table_calendar: ^3.1.2
  
  # Local Storage
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Remote Storage (Supabase)
  supabase_flutter: ^2.6.0

  # JSON
  json_annotation: ^4.8.1

  xml: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  
  # Testing
  mockito: ^5.4.2
  
  # Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

