# =============================================================================
# APP PLANTIS - ANALYSIS OPTIONS
# =============================================================================
# Herda configurações empresariais do monorepo root
# App específico: Cuidado de Plantas (Provider + Notifications + Scheduling)
# =============================================================================

# Herdar configurações empresariais do root
include: ../../analysis_options.yaml

analyzer:
  # Configurações específicas do app-plantis
  exclude:
    # Excluir arquivos específicos do app
    - "lib/firebase_options.dart"
    
linter:
  rules:
    # Overrides específicos para app-plantis se necessário
    # (manter mínimo possível para consistência)
    
    # Permitir prints em desenvolvimento (será removido em produção)
    avoid_print: false
