// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbW8MMuDEBuesAQ2-OvqqMm9quMKB0a4Y',
    appId: '1:587531440612:web:81dc341ebfefacfec5b7f1',
    messagingSenderId: '587531440612',
    projectId: 'nutrituti',
    authDomain: 'nutrituti.firebaseapp.com',
    storageBucket: 'nutrituti.appspot.com',
    measurementId: 'G-RF53YPFDQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUU1oh_Ee81dArOR12JBp7tj8B6D-cyPU',
    appId: '1:587531440612:android:8b1edb955ba6e5d1c5b7f1',
    messagingSenderId: '587531440612',
    projectId: 'nutrituti',
    storageBucket: 'nutrituti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2aBYbsYILPbYqcm38vAlYRQQUMdWpZcY',
    appId: '1:587531440612:ios:a550229bcdd0f256c5b7f1',
    messagingSenderId: '587531440612',
    projectId: 'nutrituti',
    storageBucket: 'nutrituti.appspot.com',
    iosBundleId: 'com.example.appNutrituti',
  );
}
