targets:
  $default:
    builders:
      riverpod_generator:
        options:
          # Enable code generation for Riverpod
          enabled: true
      injectable_generator:injectable_builder:
        options:
          # Enable dependency injection generation
          auto_register: true
